### DISCUSSION TITLE
How to set prometheus metrics for lotus

### DISCUSSION THREAD

**Discussion by TonyS001** [filecoin-project/lotus#11010] [General Q&A] [answered]
I run a lotus mainnet fullnode and want to run prometheus on another host. How to config it ?

**Comment by kehiy** [comment]
hello tony, you can done this in 5 easy steps

1. first of all Install Prometheus, you can download it in official [website](https://prometheus.io/download/).
2. now you need to config it with `prometheus.yml` the default location for this file depends on your operating system but its typically in Prometheus installation directory.

example of config file:
```yml
scrape_configs:
  - job_name: 'lotus'
    static_configs:
      - targets: ['<YOUR_LOTUS_NODE_IP>:<YOUR_LOTUS_NODE_EXPORTER_PORT>']

```
4. then you should save and restart Prometheus.
5. the last step is going to Prometheus web ui and you can use it now.
