### DISCUSSION TITLE
How to start lotus

### DISCUSSION THREAD

**Discussion by de-authority** [filecoin-project/lotus#7352] [Tutorials]
## How to start the program
You can run lotus in any way you are familiar with, such as screen, tmux, nohup, systemd, but it is important to make it easy to operate and to keep a good log for debugging purposes.
The following are two of the more commonly used methods,Let's take the example of running lotus-miner and explain how to run the program

### 1. nohup
You can run lotus via nohup and redirect the logs to a file. Before running this command you need to configure your environment variables

```sh
nohup lotus-miner run  >> /var/log/lotus/my-miner.log 2>&1 &
```
Here's a little tip:
When you have finished running the program, try to exit by typing exit instead of closing the terminal. Some community members have reported that closing the terminal directly causes lotus-worker to exit (assuming you run lotus-worker this way) . You can see this [discussion](https://github.com/filecoin-project/lotus/discussions/6278)

### 2. systemd
Related docs [**here**](https://docs.filecoin.io/get-started/lotus/installation/#linux) , you can install service (in the lotus source code directory) by run
```shell
sudo make install-services
```
But you need to modify the service file according to the following tips.
#### Tip 1:
Always specify the running user in the service file.And the system will not read the user's environment variables, so you have to configure all the environment variables in the service file for the application to run.
You can either configure it directly in the service file or have the service file read the environment variable file. And remember to import the program runtime environment variables into the user environment variables.
Usually you can import to ~/.bashrc /etc/profile

#### Tip 2:
You need to create the log directory manually, usually /var/log/lotus, and specify the owner of the directory as the user running the service

examples 
```toml
[Unit]
Description=Lotus Miner
After=network.target
After=lotus-daemon.service
Wants=lotus-daemon.service

[Service]
ExecStart=/usr/local/bin/lotus-miner run
EnvironmentFile=~/filecoin/miner.env
User=fil-user # you should replace fil-user with your user here
LimitNOFILE=1048576:1048576 #ulimt

[Install]
WantedBy=multi-user.target
```  

content of ~/filecoin/miner.env
```env
RUST_LOG=info
GOLOG_FILE="/var/log/lotus/miner.log"
GOLOG_LOG_FMT="json"
BELLMAN_CPU_UTILIZATION=0.875 #this value could change depend on your task type
FIL_PROOFS_MAXIMIZE_CACHING=1
FIL_PROOFS_USE_GPU_COLUMN_BUILDER=1
FIL_PROOFS_USE_GPU_TREE_BUILDER=1
TMPDIR=/you-tmp-dir # Used when sealing.
RUSTFLAGS="-C target-cpu=native -g"
FFI_BUILD_FROM_SOURCE=1 # buil time env
LOTUS_BACKUP_BASE_PATH=~/backups #Used when backup miner
```
