### ISSUE TITLE
COMPACTION ERROR, the chain is growthing

### ISSUE THREAD

**Issue by harbour015** [filecoin-project/lotus#10615]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus -v
lotus version 1.21.0-rc2+mainnet+git.caa6dd9c4
```

### Repro Steps

lotus config:

```toml
[Chainstore]
  EnableSplitstore = true
  [Chainstore.Splitstore]
    ColdStoreType = "discard"
    HotStoreFullGCFrequency = 0
    HotStoreMaxSpaceTarget = 500000000000
    HotStoreMaxSpaceThreshold = 150000000000
    HotstoreMaxSpaceSafetyBuffer = 50000000000
```

### Describe the Bug

I am using the latest snapshot to start Lotus, with the following configuration:
[Chainstore]
  EnableSplitstore = true
  [Chainstore.Splitstore]
    ColdStoreType = "discard"
    HotStoreFullGCFrequency = 0
    HotStoreMaxSpaceTarget = 500000000000
    HotStoreMaxSpaceThreshold = 150000000000
    HotstoreMaxSpaceSafetyBuffer = 50000000000
However, the chain is still growing, and I observe the following information in the logs:
![image](https://user-images.githubusercontent.com/48000268/229667668-cbaf7505-a1d7-4327-aeda-a18d25b5a361.png)

And I don't know if there is a direct correlation between them.

### Logging Information

```text
![image](https://user-images.githubusercontent.com/48000268/229667668-cbaf7505-a1d7-4327-aeda-a18d25b5a361.png)
```
