### ISSUE TITLE
[Sealing Issue] Limitations in simultaneous sealing of sectors

### ISSUE THREAD

**Issue by operate0** [filecoin-project/lotus#6216]
**Describe the problem**
When starting up to 4 sectors at the same time, only 3 are started. In miner. log it is written that there is not enough space in the fast storage. Two NVMe disks are connected to the miner and both are visible when executing the lotus-miner storage list command, but the second disk was not used in any way.

**Version**
Daemon:  1.9.0-rc3+mainnet+git.1e1e0cc93+api1.2.0
Local: lotus version 1.9.0-rc3+mainnet+git.1e1e0cc93

**Setup**

I have all-in-one system with next setup:
CPU: AMD Ryzen Threadripper 3960X
RAM: 256Gb
GPU: RTX 3090
NVMe#1 (OS+chain+256Gb swap): Corsair Force Series MP600
NVMe#2 (sealing storage #1): Corsair Force Series MP600
NVMe#3 (sealing storage #2): Corsair Force Series MP600
Longterm storage: 76Tb RAID6+LVM

Enviroment:
```
FIL_PROOFS_MAXIMIZE_CACHING=1
FIL_PROOFS_USE_GPU_COLUMN_BUILDER=1
FIL_PROOFS_USE_GPU_TREE_BUILDER=1
FIL_PROOFS_USE_MULTICORE_SDR=1

FIL_PROOFS_SDR_PARENTS_CACHE_SIZE=1073741824
FIL_PROOFS_PARAMETER_CACHE=/home/x/lotus_cache/params
FIL_PROOFS_PARENT_CACHE=/home/x/lotus_cache/parent

LOTUS_MINER_PATH=/home/x/lotus_miner
LOTUS_PATH=/home/x/.lotus

RUSTFLAGS="-C target-cpu=native -g"
FFI_BUILD_FROM_SOURCE=1
FFI_USE_GPU=1

lotus daemon start with systemctl.
lotus-miner start in shell
lotus-worker start in shell
```

**Commands**

```
lotus-miner sectors pledge
lotus-miner sectors pledge
lotus-miner sectors pledge
lotus-miner sectors pledge
```

**Sectors status**

```
44.     2021-05-08 19:42:10 +0000 UTC:  [event;sealing.SectorRetrySealPreCommit1]       {"User":{}}
45.     2021-05-08 19:42:10 +0000 UTC:  [event;sealing.SectorSealPreCommit1Failed]      {"User":{}}
        seal pre commit(1) failed: storage call error 102: can't reserve 484472310988 bytes in '/home/elbrus/lotus_sealing/' (id:a549a581-26a3-462d-99e2-906e90df0d3d), only 139514468764 available
46.     2021-05-08 19:43:10 +0000 UTC:  [event;sealing.SectorRetrySealPreCommit1]       {"User":{}}
```

**Lotus miner logs**

```
2021-05-08T19:43:10.010Z        DEBUG      stores  stores/index.go:400     not allocating on a549a581-26a3-462d-99e2-906e90df0d3d, out of space (available: 173874207132, need: 518832049356)
2021-05-08T19:43:10.013Z        DEBUG      stores  stores/index.go:400     not allocating on a549a581-26a3-462d-99e2-906e90df0d3d, out of space (available: 173874207132, need: 518832049356)
```

**Lotus miner diagnostic info**

```
0b30d53c-1e6d-4b4d-87df-dc4dd65bfc35:
        [##                                                ] 93.24 GiB/1.79 TiB 5%
        Unsealed: 0; Sealed: 0; Caches: 0; Reserved: 0 B
        Weight: 10; Use: Seal
        Local: /home/x/lotus_sealing/01
        URL: http://127.0.0.1:2345/remote

a549a581-26a3-462d-99e2-906e90df0d3d:
        [#############                                     ] 509.2 GiB/1.79 TiB 27%
        Unsealed: 4; Sealed: 0; Caches: 0; Reserved: 0 B
        Weight: 10; Use: Seal
        Local: /home/x/lotus_sealing/
        URL: http://127.0.0.1:2345/remote
        URL: http://127.0.0.1:3456/remote
```

**Comment by f8-ptrk** [comment]
what are they weights of the sealing folders?

cat .lotusminer/storage.json

**Comment by operate0** [comment]
There are no weight set:

```
{
  "StoragePaths": [
    {
      "Path": "/home/x/lotus_storage/01/"
    },
    {
      "Path": "/home/x/lotus_storage/02/"
    },
    {
      "Path": "/home/x/lotus_storage/03/"
    },
    {
      "Path": "/home/x/lotus_storage/04"
    },
    {
      "Path": "/home/x/lotus_storage/05/"
    },
    {
      "Path": "/home/x/lotus_storage/06/"
    },
    {
      "Path": "/home/x/lotus_storage/07/"
    },
    {
      "Path": "/home/x/lotus_sealing/"
    }
  ]
}
```

**Comment by Reiers** [comment]
Hi @operate0 

Thanks for the report. Im unable to reproduce the issue here.

From your `lotus-miner storage list`, I can see that one of your sealing paths are missing a URL: 

```
0b30d53c-1e6d-4b4d-87df-dc4dd65bfc35:
        [##                                                ] 93.24 GiB/1.79 TiB 5%
        Unsealed: 0; Sealed: 0; Caches: 0; Reserved: 0 B
        Weight: 10; Use: Seal
        Local: /home/x/lotus_sealing/01
        URL: http://127.0.0.1:2345/remote
        Missing* <-----

a549a581-26a3-462d-99e2-906e90df0d3d:
        [#############                                     ] 509.2 GiB/1.79 TiB 27%
        Unsealed: 4; Sealed: 0; Caches: 0; Reserved: 0 B
        Weight: 10; Use: Seal
        Local: /home/x/lotus_sealing/
        URL: http://127.0.0.1:2345/remote
        URL: http://127.0.0.1:3456/remote <-*
```
That might have cause it to not find the sealing path, if not mounted correctly. 

Closing issue ticket - if you encounter the issue again in [current release](https://github.com/filecoin-project/lotus/releases/tag/v1.15.1), please open a new ticket and provide new logs and repro steps, or ask for help in our [Discussions forum.](https://github.com/filecoin-project/lotus/discussions)
Thanks !
